version: '3'

services:

  synapse:
    build:
        context: ../..
        dockerfile: docker/Dockerfile
    image: docker.io/matrixdotorg/synapse:latest
    restart: unless-stopped
    environment:
      - SYNAPSE_SERVER_NAME=synapse.gareth.id.au
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_ENABLE_REGISTRATION=yes
      - SYNAPSE_LOG_LEVEL=INFO
      - POSTGRES_PASSWORD
    volumes:
      - /opt/synapse/data:/data
    depends_on:
      - db
    ports:
      - 443:8448/tcp
      - 8448:8448/tcp

  db:
    image: docker.io/postgres:10-alpine
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD
    volumes:
      - /opt/synapse/db:/var/lib/postgresql/data
